seuratObj <- qs_read('preclusteringSeurat.qs2')
seuratObj <- FindClusters(seuratObj, resolution=3.6, graph.name='wknn')
DimPlot(seuratObj, label=TRUE, label.size=3) + NoLegend()

seuratObj <- addMetadataCategory(seuratObj, 'seurat_clusters', 'celltype',
                              list(c(0, 1, 8, 28, 32, 16, 17, 31, 35, 10),
                                   c(2, 39, 5, 20, 26, 37, 38, 
                                     33, 14, 22, 9, 11, 24),
                                   3, 
                                   4, 
                                   c(6, 29, 18),
                                   7,
                                   c(12, 15, 25),
                                   c(13, 44),
                                   19,
                                   21,
                                   23, 
                                   27,
                                   34, 
                                   36,
                                   40, 
                                   42, 
                                   43),
                              c('Cones',
                                'Retinal progenitor cells',
                                'Bipolar cells',
                                'RPE cells',
                                'Rods',
                                'Muller glial cells',
                                'PRDM13+ amacrine cells',
                                'Photoreceptor precursors',
                                'Early retinal progenitor cells',
                                'KCNH7+ retinal ganglion cells',
                                'Horizontal cells',
                                'Neurogenic progenitors',
                                'HTR2C+ retinal ganglion cells',
                                'ISL1+ retinal ganglion cells',
                                'NEUROD6+ retinal ganglion cells',
                                'Mesenchymal-like cells',
                                'Myocyte-like'),
                              'topMarkers',
                              c('PDE6H/MPP4/RIMS2',
                                'SFRP2/DAPL1/HES1',
                                'CA10/CSMD3/VSX1',
                                'TRPM1/CD96/TYR',
                                'NRL/NR2E3/ROM1',
                                'FLT1/TF/WIF1',
                                'PRDM13/TFAP2A/TFAP2B', 
                                'PRDM1/VXN/LHX4',
                                'TOP2A/CENPF/MKI67',
                                'KCNH7/KCNIP1/KCNC2',
                                'ONECUT1/ONECUT2/ONECUT3',
                                'HES6/ATOH2/INSM1',
                                'HTR2C/FYB2/EMX2',
                                'ISL1/POU4F1/POU4F2',
                                'NEUROD6/NEUROD2/POU3F3',
                                'COL1A1/COL3A1/COL1A2',
                                'TNNT2/DES/MYL1'))

